# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32c82989a7b7ccfd973734ccf451335bc9f9254b8b007eb311a0dd31caa6ef690821265ac12105a5c3c5b1182f77f4642fa00dcfbc46511f6ae6cbe61996c28f

test:
  secret_key_base: ecccc9ced2e13f7c8bef9a419a8b4a1317fb8ebb11eca3698a0f05abee4f4746006307d2c704ad47b0f470a8e07a7912b2c688435f42d6dc1f874007c246ab9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
