# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Rails.env == "development" || Rails.env == "test"
  puts "Cleaning DB first ..."
  Menu.destroy_all
  Recipe.destroy_all
  Ingredient.destroy_all
end

puts "creating grocery items"
Grocery.create!([
  {name: "woolwash", section: "laundry"},
  {name: "floor cleaner", section: "laundry"},
  {name: "laundry detergent", section: "other"}
])

puts "creating ingredients"
Ingredient.create!([
  {name: "allspice", shop_section: "spices"},
  {name: "baking powder", shop_section: "baking"},
  {name: "bay leaves", shop_section: "spices"},
  {name: "broccoli", shop_section: "fruit and veg"},
  {name: "brown sugar", shop_section: "baking"},
  {name: "bulghur", shop_section: "baking"},
  {name: "butter", shop_section: "dairy"},
  {name: "capers", shop_section: "tinned goods"},
  {name: "cardamom pods", shop_section: "spices"},
  {name: "carrot", shop_section: "fruit and veg"},
  {name: "cauliflower", shop_section: "fruit and veg"},
  {name: "celery", shop_section: "fruit and veg"},
  {name: "cheddar", shop_section: "dairy"},
  {name: "chilli powder", shop_section: "spices"},
  {name: "chilli sauce", shop_section: "condiments"},
  {name: "chillies", shop_section: "fruit and veg"},
  {name: "cinnamon", shop_section: "spices"},
  {name: "cloves", shop_section: "spices"},
  {name: "coriander", shop_section: "fruit and veg"},
  {name: "coriander powder", shop_section: "spices"},
  {name: "creme fraiche", shop_section: "dairy"},
  {name: "cumin seeds", shop_section: "spices"},
  {name: "curry leaves", shop_section: "spices"},
  {name: "dill", shop_section: "fruit and veg"},
  {name: "egg", shop_section: "dairy"},
  {name: "eggplant", shop_section: "tinned goods"},
  {name: "fennel", shop_section: "fruit and veg"},
  {name: "fetta", shop_section: "dairy"},
  {name: "filo", shop_section: "bread, pasta and pastry"},
  {name: "flatbreads", shop_section: "bread, pasta and pastry"},
  {name: "flour", shop_section: "baking"},
  {name: "frozen peas", shop_section: "frozen"},
  {name: "frozen spinach", shop_section: "frozen"},
  {name: "garlic", shop_section: "fruit and veg"},
  {name: "ginger", shop_section: "fruit and veg"},
  {name: "goat cheese", shop_section: "dairy"},
  {name: "gorgonzola", shop_section: "dairy"},
  {name: "green olives", shop_section: "tinned goods"},
  {name: "heavy cream", shop_section: "dairy"},
  {name: "hokkien noodles", shop_section: "bread, pasta and pastry"},
  {name: "kasoori methi", shop_section: "spices"},
  {name: "leeks", shop_section: "fruit and veg"},
  {name: "lemon", shop_section: "fruit and veg"},
  {name: "lime", shop_section: "fruit and veg"},
  {name: "linguine", shop_section: "bread, pasta and pastry"},
  {name: "marjoram", shop_section: "spices"},
  {name: "milk", shop_section: "dairy"},
  {name: "mint", shop_section: "fruit and veg"},
  {name: "mozzarella", shop_section: "dairy"},
  {name: "mushroom", shop_section: "fruit and veg"},
  {name: "mustard seeds", shop_section: "spices"},
  {name: "nutmeg", shop_section: "spices"},
  {name: "olive oil", shop_section: "tinned goods"},
  {name: "onions", shop_section: "fruit and veg"},
  {name: "oregano", shop_section: "fruit and veg"},
  {name: "orzo", shop_section: "dairy"},
  {name: "panch phora", shop_section: "spices"},
  {name: "parmesan", shop_section: "dairy"},
  {name: "parsley", shop_section: "fruit and veg"},
  {name: "pasta", shop_section: "bread, pasta and pastry"},
  {name: "pastry shell", shop_section: "bread, pasta and pastry"},
  {name: "pecorino", shop_section: "dairy"},
  {name: "peppercorns", shop_section: "spices"},
  {name: "potatoes", shop_section: "fruit and veg"},
  {name: "red onion", shop_section: "fruit and veg"},
  {name: "red peppers", shop_section: "fruit and veg"},
  {name: "rice noodles", shop_section: "bread, pasta and pastry"},
  {name: "rocket", shop_section: "fruit and veg"},
  {name: "salted peanuts", shop_section: "nuts"},
  {name: "scallions", shop_section: "fruit and veg"},
  {name: "shahi jeera", shop_section: "spices"},
  {name: "sour cream", shop_section: "dairy"},
  {name: "soy sauce", shop_section: "condiments"},
  {name: "spring onions", shop_section: "fruit and veg"},
  {name: "sriracha", shop_section: "condiments"},
  {name: "star anise", shop_section: "spices"},
  {name: "swiss cheese", shop_section: "dairy"},
  {name: "tarragon", shop_section: "fruit and veg"},
  {name: "tin lentils", shop_section: "tinned goods"},
  {name: "tin tomatoes", shop_section: "cleaning"},
  {name: "tofu (fried)", shop_section: "cleaning"},
  {name: "tofu (hard)", shop_section: "market"},
  {name: "tomato", shop_section: "fruit and veg"},
  {name: "tomato paste", shop_section: "tinned goods"},
  {name: "tomato sauce ", shop_section: "condiments"},
  {name: "tumeric", shop_section: "spices"},
  {name: "vegetable oil", shop_section: "fruit and veg"},
  {name: "vegetable stock", shop_section: "bread"},
  {name: "walnuts", shop_section: "nuts"},
  {name: "white vinegar", shop_section: "condiments"},
  {name: "yoghurt", shop_section: "dairy"},
  {name: "pumpkin", shop_section: "fruit and veg"},
  {name: "flatbread", shop_section: "bread, pasta and pastry"},
  {name: "pinenuts", shop_section: "nuts"},
  {name: "frozen peas", shop_section: "frozen"},
  {name: "capsicum", shop_section: "fruit and veg"},
  {name: "roasted capsicum", shop_section: "dairy"},
  {name: "Zucchini", shop_section: "fruit and veg"},
  {name: "Coconut", shop_section: "baking"},
  {name: "Tomatoes - sun dried", shop_section: "tinned goods"},
  {name: "Basil", shop_section: "fruit and veg"},
  {name: "Radish", shop_section: "fruit and veg"},
  {name: "Mustard", shop_section: "tinned goods"},
  {name: "Lentils", shop_section: "tinned goods"},
  {name: "Salad", shop_section: "fruit and veg"},
  {name: "Olives", shop_section: "tinned goods"},
  {name: "Bread -baguette", shop_section: "bread, pasta and pastry"},
  {name: "Shortcrust pastry", shop_section: "bread, pasta and pastry"},
  {name: "Puff pastry", shop_section: "bread, pasta and pastry"},
  {name: "Stock", shop_section: "spices"},
  {name: "Rice", shop_section: "bread, pasta and pastry"}
])

puts "creating recipes"
Recipe.create!([
  {name: "baked eggplant pasta", recipe_category: "rice", recipe_type: "main", chef: "Cat"},
  {name: "baked tomato pasta sauce", recipe_category: "salad", recipe_type: "side", chef: "Tom"},
  {name: "bechamel and roast veg", recipe_category: "pasta", recipe_type: "dessert", chef: "Cat"},
  {name: "bowl o veg", recipe_category: "other", recipe_type: "main", chef: "Tom"},
  {name: "caponata", recipe_category: "salad", recipe_type: "dessert", chef: "Cat"},
  {name: "cauliflower cheese", recipe_category: "other", recipe_type: "dessert", chef: "Cat"},
  {name: "fennel salad", recipe_category: "rice", recipe_type: "main", chef: "Cat"},
  {name: "fried rice", recipe_category: "salad", recipe_type: "schoolnight", chef: "Tom"},
  {name: "frittata", recipe_category: "pasta", recipe_type: "schoolnight", chef: "Tom"},
  {name: "fritters (broccoli)", recipe_category: "salad", recipe_type: "schoolnight", chef: "Cat"},
  {name: "fritters (cauliflower)", recipe_category: "soup", recipe_type: "side", chef: "Tom"},
  {name: "grain salad", recipe_category: "pasta", recipe_type: "schoolnight", chef: "Cat"},
  {name: "laksa soup", recipe_category: "pasta", recipe_type: "main", chef: "Cat"},
  {name: "macaroni cheese", recipe_category: "salad", recipe_type: "dessert", chef: "Cat"},
  {name: "margarita pizza", recipe_category: "pasta", recipe_type: "dessert", chef: "Cat"},
  {name: "mee goreng", recipe_category: "pasta", recipe_type: "potheavy", chef: "Cat"},
  {name: "mushroom and pesto pizza", recipe_category: "soup", recipe_type: "main", chef: "Cat"},
  {name: "muttar paneer", recipe_category: "rice", recipe_type: "main", chef: "Tom"},
  {name: "pad thai", recipe_category: "salad", recipe_type: "potheavy", chef: "Tom"},
  {name: "pakora", recipe_category: "salad", recipe_type: "dessert", chef: "Cat"},
  {name: "palak gobi", recipe_category: "other", recipe_type: "potheavy", chef: "Tom"},
  {name: "pumpkin soup", recipe_category: "pasta", recipe_type: "main", chef: "Tom"},
  {name: "risotto (mushroom)", recipe_category: "rice", recipe_type: "main", chef: "Cat"},
  {name: "saag paneer", recipe_category: "rice", recipe_type: "dessert", chef: "Tom"},
  {name: "samosas", recipe_category: "rice", recipe_type: "main", chef: "Cat"},
  {name: "spanakopita", recipe_category: "soup", recipe_type: "side", chef: "Cat"},
  {name: "tabbouleh", recipe_category: "pasta", recipe_type: "dessert", chef: "Cat"},
  {name: "tex mex", recipe_category: "pasta", recipe_type: "main", chef: "Tom"},
  {name: "veggie pasta", recipe_category: "pasta", recipe_type: "schoolnight", chef: "Cat"},
  {name: "dahl", recipe_category: "rice", recipe_type: "main", chef: "Tom"},
  {name: "baked leek and walnut penne", recipe_category: "pasta", recipe_type: "main", chef: "Tom"},
  {name: "red pepper alfredo", recipe_category: "pasta", recipe_type: "main", chef: "Cat"},
  {name: "pasta mozzarella salad", recipe_category: "salad", recipe_type: "main", chef: "Cat"},
  {name: "Butternut squash alfredo", recipe_category: "pasta", recipe_type: "main", chef: "Cat"},
  {name: "Zucchini coconut curry", recipe_category: "rice", recipe_type: "main", chef: "Tom"},
  {name: "broccoli chilli pasta", recipe_category: "pasta", recipe_type: "schoolnight", chef: "Cat"},
  {name: "shepherd pie", recipe_category: "other", recipe_type: "main", chef: "Cat"},
  {name: "mushroom quiche", recipe_category: "other", recipe_type: "main", chef: "Cat"},
  {name: "red pepper soup", recipe_category: "soup", recipe_type: "schoolnight", chef: "Cat"},
  {name: "veggie soup", recipe_category: "soup", recipe_type: "main", chef: "Cat"},
  {name: "Caramelised onion quiche with steamed veg", recipe_category: "other", recipe_type: "main", chef: "Cat"},
  {name: "fritters (zucchini)", recipe_category: "other", recipe_type: "main", chef: "Cat"},
  {name: "Aloo gobi biryani", recipe_category: "rice", recipe_type: "main", chef: "Cat"}
])

puts "creating menus"
Menu.create!([
  {name: "Menu No. 1"},
  {name: "Menu No. 2"},
  {name: "Menu No. 3"},
  {name: "Menu No. 4"},
  {name: "Menu No. 5"},
  {name: "Menu for 01 Dec, 2014"},
  {name: "Menu for 08 dec, 2014"},
  {name: "Menu for 08 dec, 2014"},
  {name: "Menu for 15 dec, 2014"},
  {name: "Menu for 05 jan, 2015"},
  {name: "Menu for 12 jan, 2015"}
])

puts "creating ingredients habtm recipes"
Ingredient::HABTM_Recipes.create!([
  {ingredient_id: 21, recipe_id: 3},
  {ingredient_id: 42, recipe_id: 3},
  {ingredient_id: 54, recipe_id: 3},
  {ingredient_id: 60, recipe_id: 3},
  {ingredient_id: 78, recipe_id: 3},
  {ingredient_id: 89, recipe_id: 3},
  {ingredient_id: 7, recipe_id: 10},
  {ingredient_id: 14, recipe_id: 10},
  {ingredient_id: 54, recipe_id: 10},
  {ingredient_id: 79, recipe_id: 10},
  {ingredient_id: 80, recipe_id: 10},
  {ingredient_id: 86, recipe_id: 10},
  {ingredient_id: 91, recipe_id: 10},
  {ingredient_id: 10, recipe_id: 28},
  {ingredient_id: 49, recipe_id: 28},
  {ingredient_id: 58, recipe_id: 28},
  {ingredient_id: 60, recipe_id: 28},
  {ingredient_id: 21, recipe_id: 30},
  {ingredient_id: 58, recipe_id: 30},
  {ingredient_id: 60, recipe_id: 30},
  {ingredient_id: 63, recipe_id: 30},
  {ingredient_id: 32, recipe_id: 3},
  {ingredient_id: 30, recipe_id: 10},
  {ingredient_id: 94, recipe_id: 28},
  {ingredient_id: 97, recipe_id: 30},
  {ingredient_id: 34, recipe_id: 30},
  {ingredient_id: 54, recipe_id: 30},
  {ingredient_id: 21, recipe_id: 41},
  {ingredient_id: 28, recipe_id: 41},
  {ingredient_id: 60, recipe_id: 41},
  {ingredient_id: 92, recipe_id: 41},
  {ingredient_id: 99, recipe_id: 42},
  {ingredient_id: 34, recipe_id: 42},
  {ingredient_id: 35, recipe_id: 42},
  {ingredient_id: 54, recipe_id: 42},
  {ingredient_id: 80, recipe_id: 42},
  {ingredient_id: 98, recipe_id: 42},
  {ingredient_id: 101, recipe_id: 28},
  {ingredient_id: 102, recipe_id: 28},
  {ingredient_id: 100, recipe_id: 28},
  {ingredient_id: 4, recipe_id: 7},
  {ingredient_id: 16, recipe_id: 7},
  {ingredient_id: 34, recipe_id: 7},
  {ingredient_id: 54, recipe_id: 7},
  {ingredient_id: 58, recipe_id: 7},
  {ingredient_id: 60, recipe_id: 7},
  {ingredient_id: 89, recipe_id: 7},
  {ingredient_id: 7, recipe_id: 9},
  {ingredient_id: 10, recipe_id: 9},
  {ingredient_id: 11, recipe_id: 9},
  {ingredient_id: 13, recipe_id: 9},
  {ingredient_id: 47, recipe_id: 9},
  {ingredient_id: 58, recipe_id: 9},
  {ingredient_id: 59, recipe_id: 9},
  {ingredient_id: 103, recipe_id: 9},
  {ingredient_id: 10, recipe_id: 35},
  {ingredient_id: 12, recipe_id: 35},
  {ingredient_id: 95, recipe_id: 35},
  {ingredient_id: 104, recipe_id: 35},
  {ingredient_id: 54, recipe_id: 35},
  {ingredient_id: 63, recipe_id: 35},
  {ingredient_id: 64, recipe_id: 35},
  {ingredient_id: 73, recipe_id: 35},
  {ingredient_id: 77, recipe_id: 35},
  {ingredient_id: 80, recipe_id: 35},
  {ingredient_id: 96, recipe_id: 6},
  {ingredient_id: 10, recipe_id: 6},
  {ingredient_id: 12, recipe_id: 6},
  {ingredient_id: 28, recipe_id: 6},
  {ingredient_id: 89, recipe_id: 6},
  {ingredient_id: 105, recipe_id: 6},
  {ingredient_id: 106, recipe_id: 28},
  {ingredient_id: 107, recipe_id: 6},
  {ingredient_id: 91, recipe_id: 42},
  {ingredient_id: 21, recipe_id: 23},
  {ingredient_id: 42, recipe_id: 23},
  {ingredient_id: 50, recipe_id: 23},
  {ingredient_id: 7, recipe_id: 23},
  {ingredient_id: 25, recipe_id: 23},
  {ingredient_id: 33, recipe_id: 23},
  {ingredient_id: 34, recipe_id: 23},
  {ingredient_id: 77, recipe_id: 23},
  {ingredient_id: 108, recipe_id: 23},
  {ingredient_id: 34, recipe_id: 31},
  {ingredient_id: 54, recipe_id: 31},
  {ingredient_id: 97, recipe_id: 31},
  {ingredient_id: 80, recipe_id: 31},
  {ingredient_id: 110, recipe_id: 31},
  {ingredient_id: 107, recipe_id: 40},
  {ingredient_id: 4, recipe_id: 40},
  {ingredient_id: 96, recipe_id: 40},
  {ingredient_id: 10, recipe_id: 40},
  {ingredient_id: 27, recipe_id: 40},
  {ingredient_id: 34, recipe_id: 40},
  {ingredient_id: 42, recipe_id: 40},
  {ingredient_id: 54, recipe_id: 40},
  {ingredient_id: 55, recipe_id: 40},
  {ingredient_id: 58, recipe_id: 40},
  {ingredient_id: 60, recipe_id: 40},
  {ingredient_id: 110, recipe_id: 40},
  {ingredient_id: 80, recipe_id: 40},
  {ingredient_id: 95, recipe_id: 34},
  {ingredient_id: 34, recipe_id: 34},
  {ingredient_id: 35, recipe_id: 34},
  {ingredient_id: 64, recipe_id: 34},
  {ingredient_id: 109, recipe_id: 34},
  {ingredient_id: 91, recipe_id: 34},
  {ingredient_id: 3, recipe_id: 40},
  {ingredient_id: 93, recipe_id: 42},
  {ingredient_id: 4, recipe_id: 43},
  {ingredient_id: 7, recipe_id: 43},
  {ingredient_id: 10, recipe_id: 43},
  {ingredient_id: 21, recipe_id: 43},
  {ingredient_id: 25, recipe_id: 43},
  {ingredient_id: 95, recipe_id: 43},
  {ingredient_id: 34, recipe_id: 43},
  {ingredient_id: 54, recipe_id: 43},
  {ingredient_id: 58, recipe_id: 43},
  {ingredient_id: 108, recipe_id: 43},
  {ingredient_id: 77, recipe_id: 43},
  {ingredient_id: 16, recipe_id: 16},
  {ingredient_id: 19, recipe_id: 16},
  {ingredient_id: 24, recipe_id: 16},
  {ingredient_id: 25, recipe_id: 16},
  {ingredient_id: 28, recipe_id: 16},
  {ingredient_id: 31, recipe_id: 16},
  {ingredient_id: 91, recipe_id: 16},
  {ingredient_id: 98, recipe_id: 16},
  {ingredient_id: 48, recipe_id: 16},
  {ingredient_id: 3, recipe_id: 1},
  {ingredient_id: 9, recipe_id: 1},
  {ingredient_id: 11, recipe_id: 1},
  {ingredient_id: 14, recipe_id: 1},
  {ingredient_id: 17, recipe_id: 1},
  {ingredient_id: 18, recipe_id: 1},
  {ingredient_id: 19, recipe_id: 1},
  {ingredient_id: 20, recipe_id: 1},
  {ingredient_id: 22, recipe_id: 1},
  {ingredient_id: 95, recipe_id: 1},
  {ingredient_id: 34, recipe_id: 1},
  {ingredient_id: 35, recipe_id: 1},
  {ingredient_id: 41, recipe_id: 1},
  {ingredient_id: 48, recipe_id: 1},
  {ingredient_id: 54, recipe_id: 1},
  {ingredient_id: 63, recipe_id: 1},
  {ingredient_id: 64, recipe_id: 1},
  {ingredient_id: 71, recipe_id: 1},
  {ingredient_id: 76, recipe_id: 1},
  {ingredient_id: 91, recipe_id: 1},
  {ingredient_id: 7, recipe_id: 1},
  {ingredient_id: 86, recipe_id: 1},
  {ingredient_id: 111, recipe_id: 1}
])

puts "creating menus habtm recipes"
Menu::HABTM_Recipes.create!([
  {menu_id: 1, recipe_id: 40},
  {menu_id: 1, recipe_id: 2},
  {menu_id: 1, recipe_id: 2},
  {menu_id: 1, recipe_id: 1},
  {menu_id: 2, recipe_id: 38},
  {menu_id: 2, recipe_id: 6},
  {menu_id: 2, recipe_id: 4},
  {menu_id: 2, recipe_id: 4},
  {menu_id: 3, recipe_id: 35},
  {menu_id: 3, recipe_id: 35},
  {menu_id: 3, recipe_id: 2},
  {menu_id: 3, recipe_id: 32},
  {menu_id: 4, recipe_id: 31},
  {menu_id: 4, recipe_id: 16},
  {menu_id: 4, recipe_id: 19},
  {menu_id: 4, recipe_id: 26},
  {menu_id: 5, recipe_id: 25},
  {menu_id: 5, recipe_id: 22},
  {menu_id: 5, recipe_id: 4},
  {menu_id: 5, recipe_id: 36},
  {menu_id: 6, recipe_id: 3},
  {menu_id: 6, recipe_id: 10},
  {menu_id: 6, recipe_id: 28},
  {menu_id: 6, recipe_id: 30},
  {menu_id: 7, recipe_id: 6},
  {menu_id: 7, recipe_id: 7},
  {menu_id: 7, recipe_id: 9},
  {menu_id: 7, recipe_id: 35},
  {menu_id: 7, recipe_id: 28},
  {menu_id: 7, recipe_id: 42},
  {menu_id: 8, recipe_id: 6},
  {menu_id: 8, recipe_id: 7},
  {menu_id: 8, recipe_id: 9},
  {menu_id: 8, recipe_id: 35},
  {menu_id: 8, recipe_id: 28},
  {menu_id: 8, recipe_id: 42},
  {menu_id: 9, recipe_id: 23},
  {menu_id: 9, recipe_id: 31},
  {menu_id: 9, recipe_id: 34},
  {menu_id: 9, recipe_id: 40},
  {menu_id: 9, recipe_id: 42},
  {menu_id: 11, recipe_id: 28},
  {menu_id: 11, recipe_id: 42},
  {menu_id: 11, recipe_id: 40},
  {menu_id: 12, recipe_id: 16},
  {menu_id: 12, recipe_id: 10},
  {menu_id: 12, recipe_id: 28},
  {menu_id: 12, recipe_id: 31},
  {menu_id: 12, recipe_id: 43},
  {menu_id: 12, recipe_id: 1}
])

puts "creating recipes habtm ingredients"
Recipe::HABTM_Ingredients.create!([
  {ingredient_id: 21, recipe_id: 3},
  {ingredient_id: 42, recipe_id: 3},
  {ingredient_id: 54, recipe_id: 3},
  {ingredient_id: 60, recipe_id: 3},
  {ingredient_id: 78, recipe_id: 3},
  {ingredient_id: 89, recipe_id: 3},
  {ingredient_id: 7, recipe_id: 10},
  {ingredient_id: 14, recipe_id: 10},
  {ingredient_id: 54, recipe_id: 10},
  {ingredient_id: 79, recipe_id: 10},
  {ingredient_id: 80, recipe_id: 10},
  {ingredient_id: 86, recipe_id: 10},
  {ingredient_id: 91, recipe_id: 10},
  {ingredient_id: 10, recipe_id: 28},
  {ingredient_id: 49, recipe_id: 28},
  {ingredient_id: 58, recipe_id: 28},
  {ingredient_id: 60, recipe_id: 28},
  {ingredient_id: 21, recipe_id: 30},
  {ingredient_id: 58, recipe_id: 30},
  {ingredient_id: 60, recipe_id: 30},
  {ingredient_id: 63, recipe_id: 30},
  {ingredient_id: 32, recipe_id: 3},
  {ingredient_id: 30, recipe_id: 10},
  {ingredient_id: 94, recipe_id: 28},
  {ingredient_id: 97, recipe_id: 30},
  {ingredient_id: 34, recipe_id: 30},
  {ingredient_id: 54, recipe_id: 30},
  {ingredient_id: 21, recipe_id: 41},
  {ingredient_id: 28, recipe_id: 41},
  {ingredient_id: 60, recipe_id: 41},
  {ingredient_id: 92, recipe_id: 41},
  {ingredient_id: 99, recipe_id: 42},
  {ingredient_id: 34, recipe_id: 42},
  {ingredient_id: 35, recipe_id: 42},
  {ingredient_id: 54, recipe_id: 42},
  {ingredient_id: 80, recipe_id: 42},
  {ingredient_id: 98, recipe_id: 42},
  {ingredient_id: 101, recipe_id: 28},
  {ingredient_id: 102, recipe_id: 28},
  {ingredient_id: 100, recipe_id: 28},
  {ingredient_id: 4, recipe_id: 7},
  {ingredient_id: 16, recipe_id: 7},
  {ingredient_id: 34, recipe_id: 7},
  {ingredient_id: 54, recipe_id: 7},
  {ingredient_id: 58, recipe_id: 7},
  {ingredient_id: 60, recipe_id: 7},
  {ingredient_id: 89, recipe_id: 7},
  {ingredient_id: 7, recipe_id: 9},
  {ingredient_id: 10, recipe_id: 9},
  {ingredient_id: 11, recipe_id: 9},
  {ingredient_id: 13, recipe_id: 9},
  {ingredient_id: 47, recipe_id: 9},
  {ingredient_id: 58, recipe_id: 9},
  {ingredient_id: 59, recipe_id: 9},
  {ingredient_id: 103, recipe_id: 9},
  {ingredient_id: 10, recipe_id: 35},
  {ingredient_id: 12, recipe_id: 35},
  {ingredient_id: 95, recipe_id: 35},
  {ingredient_id: 104, recipe_id: 35},
  {ingredient_id: 54, recipe_id: 35},
  {ingredient_id: 63, recipe_id: 35},
  {ingredient_id: 64, recipe_id: 35},
  {ingredient_id: 73, recipe_id: 35},
  {ingredient_id: 77, recipe_id: 35},
  {ingredient_id: 80, recipe_id: 35},
  {ingredient_id: 96, recipe_id: 6},
  {ingredient_id: 10, recipe_id: 6},
  {ingredient_id: 12, recipe_id: 6},
  {ingredient_id: 28, recipe_id: 6},
  {ingredient_id: 89, recipe_id: 6},
  {ingredient_id: 105, recipe_id: 6},
  {ingredient_id: 106, recipe_id: 28},
  {ingredient_id: 107, recipe_id: 6},
  {ingredient_id: 91, recipe_id: 42},
  {ingredient_id: 21, recipe_id: 23},
  {ingredient_id: 42, recipe_id: 23},
  {ingredient_id: 50, recipe_id: 23},
  {ingredient_id: 7, recipe_id: 23},
  {ingredient_id: 25, recipe_id: 23},
  {ingredient_id: 33, recipe_id: 23},
  {ingredient_id: 34, recipe_id: 23},
  {ingredient_id: 77, recipe_id: 23},
  {ingredient_id: 108, recipe_id: 23},
  {ingredient_id: 34, recipe_id: 31},
  {ingredient_id: 54, recipe_id: 31},
  {ingredient_id: 97, recipe_id: 31},
  {ingredient_id: 80, recipe_id: 31},
  {ingredient_id: 110, recipe_id: 31},
  {ingredient_id: 107, recipe_id: 40},
  {ingredient_id: 4, recipe_id: 40},
  {ingredient_id: 96, recipe_id: 40},
  {ingredient_id: 10, recipe_id: 40},
  {ingredient_id: 27, recipe_id: 40},
  {ingredient_id: 34, recipe_id: 40},
  {ingredient_id: 42, recipe_id: 40},
  {ingredient_id: 54, recipe_id: 40},
  {ingredient_id: 55, recipe_id: 40},
  {ingredient_id: 58, recipe_id: 40},
  {ingredient_id: 60, recipe_id: 40},
  {ingredient_id: 110, recipe_id: 40},
  {ingredient_id: 80, recipe_id: 40},
  {ingredient_id: 95, recipe_id: 34},
  {ingredient_id: 34, recipe_id: 34},
  {ingredient_id: 35, recipe_id: 34},
  {ingredient_id: 64, recipe_id: 34},
  {ingredient_id: 109, recipe_id: 34},
  {ingredient_id: 91, recipe_id: 34},
  {ingredient_id: 3, recipe_id: 40},
  {ingredient_id: 93, recipe_id: 42},
  {ingredient_id: 4, recipe_id: 43},
  {ingredient_id: 7, recipe_id: 43},
  {ingredient_id: 10, recipe_id: 43},
  {ingredient_id: 21, recipe_id: 43},
  {ingredient_id: 25, recipe_id: 43},
  {ingredient_id: 95, recipe_id: 43},
  {ingredient_id: 34, recipe_id: 43},
  {ingredient_id: 54, recipe_id: 43},
  {ingredient_id: 58, recipe_id: 43},
  {ingredient_id: 108, recipe_id: 43},
  {ingredient_id: 77, recipe_id: 43},
  {ingredient_id: 16, recipe_id: 16},
  {ingredient_id: 19, recipe_id: 16},
  {ingredient_id: 24, recipe_id: 16},
  {ingredient_id: 25, recipe_id: 16},
  {ingredient_id: 28, recipe_id: 16},
  {ingredient_id: 31, recipe_id: 16},
  {ingredient_id: 91, recipe_id: 16},
  {ingredient_id: 98, recipe_id: 16},
  {ingredient_id: 48, recipe_id: 16},
  {ingredient_id: 3, recipe_id: 1},
  {ingredient_id: 9, recipe_id: 1},
  {ingredient_id: 11, recipe_id: 1},
  {ingredient_id: 14, recipe_id: 1},
  {ingredient_id: 17, recipe_id: 1},
  {ingredient_id: 18, recipe_id: 1},
  {ingredient_id: 19, recipe_id: 1},
  {ingredient_id: 20, recipe_id: 1},
  {ingredient_id: 22, recipe_id: 1},
  {ingredient_id: 95, recipe_id: 1},
  {ingredient_id: 34, recipe_id: 1},
  {ingredient_id: 35, recipe_id: 1},
  {ingredient_id: 41, recipe_id: 1},
  {ingredient_id: 48, recipe_id: 1},
  {ingredient_id: 54, recipe_id: 1},
  {ingredient_id: 63, recipe_id: 1},
  {ingredient_id: 64, recipe_id: 1},
  {ingredient_id: 71, recipe_id: 1},
  {ingredient_id: 76, recipe_id: 1},
  {ingredient_id: 91, recipe_id: 1},
  {ingredient_id: 7, recipe_id: 1},
  {ingredient_id: 86, recipe_id: 1},
  {ingredient_id: 111, recipe_id: 1}
])

puts "creating recipes habtm menus"
Recipe::HABTM_Menus.create!([
  {menu_id: 1, recipe_id: 40},
  {menu_id: 1, recipe_id: 2},
  {menu_id: 1, recipe_id: 2},
  {menu_id: 1, recipe_id: 1},
  {menu_id: 2, recipe_id: 38},
  {menu_id: 2, recipe_id: 6},
  {menu_id: 2, recipe_id: 4},
  {menu_id: 2, recipe_id: 4},
  {menu_id: 3, recipe_id: 35},
  {menu_id: 3, recipe_id: 35},
  {menu_id: 3, recipe_id: 2},
  {menu_id: 3, recipe_id: 32},
  {menu_id: 4, recipe_id: 31},
  {menu_id: 4, recipe_id: 16},
  {menu_id: 4, recipe_id: 19},
  {menu_id: 4, recipe_id: 26},
  {menu_id: 5, recipe_id: 25},
  {menu_id: 5, recipe_id: 22},
  {menu_id: 5, recipe_id: 4},
  {menu_id: 5, recipe_id: 36},
  {menu_id: 6, recipe_id: 3},
  {menu_id: 6, recipe_id: 10},
  {menu_id: 6, recipe_id: 28},
  {menu_id: 6, recipe_id: 30},
  {menu_id: 7, recipe_id: 6},
  {menu_id: 7, recipe_id: 7},
  {menu_id: 7, recipe_id: 9},
  {menu_id: 7, recipe_id: 35},
  {menu_id: 7, recipe_id: 28},
  {menu_id: 7, recipe_id: 42},
  {menu_id: 8, recipe_id: 6},
  {menu_id: 8, recipe_id: 7},
  {menu_id: 8, recipe_id: 9},
  {menu_id: 8, recipe_id: 35},
  {menu_id: 8, recipe_id: 28},
  {menu_id: 8, recipe_id: 42},
  {menu_id: 9, recipe_id: 23},
  {menu_id: 9, recipe_id: 31},
  {menu_id: 9, recipe_id: 34},
  {menu_id: 9, recipe_id: 40},
  {menu_id: 9, recipe_id: 42},
  {menu_id: 11, recipe_id: 28},
  {menu_id: 11, recipe_id: 42},
  {menu_id: 11, recipe_id: 40},
  {menu_id: 12, recipe_id: 16},
  {menu_id: 12, recipe_id: 10},
  {menu_id: 12, recipe_id: 28},
  {menu_id: 12, recipe_id: 31},
  {menu_id: 12, recipe_id: 43},
  {menu_id: 12, recipe_id: 1}
])

puts "creating user"
user = User.create!(:name => 'Cat B', :email => 'cat1788@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret')
